---
# This playbook will install Apache and PHP dependencies

- name: Install apache and PHP packages
  action: apt pkg={{ item }} state=present
  with_items:
   - apache2
   - php5
   - libapache2-mod-php5
   - php5-xdebug
